import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/layout/Layout";
import HomeLayout from "@/components/NestedLayouts/HomeLayout";
import Hero from "@/components/homescreen/hero/Hero";
import HeroBottom from "@/components/homescreen/hero/HeroBottom";
import Posts from "@/components/homescreen/posts/Posts";
import { client } from "@/lib/client";
import { Post } from "@/typings/typings";

interface Props{
  posts: [Post]
}

const inter = Inter({ subsets: ["latin"] });

export default function Home({posts}: Props) {
  // console.log(posts);
  return (
    <>
      <Head>
        <title>blog app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <HomeLayout>
            <Hero />
            <HeroBottom />
            <Posts posts={posts} />
          </HomeLayout>
        </Layout>
      </main>
    </>
  );
}


export const getServerSideProps = async () => {
  // home screen
  const queryPosts = `*[_type == "post"] | order(_updatedAt desc){
    _id,
    title,
    author ->{
      name,
      image
    },
    categories -> {
      title,
      description
    },
    description,
    mainImage,
    slug
  }`
  const posts = await client.fetch(queryPosts);

  



  return {
    props: {
     posts,
    },
  };
};
